
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - schedule.openi.cn
  resources:
  - testjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - schedule.openi.cn
  resources:
  - testjobs/status
  verbs:
  - get
  - patch
  - update
